Lugones nicolas
alkemyTech/OT235-python pull request #16
Opened 2022-06-28 23:31 UTC by lugonesnicolas

Un poco de lo que fui haciendo, me faltan algunos detalles.

2022-06-29 01:59 UTC, juanmbntz requested changes
Nico, dos comentarios:

1. A la función de extracción le falta una parte para procesar el segundo archivo csv?
2. Tratá de agregar mas comentarios en el código. Si bien esto son poquitas líneas y se entiende lo que pasa en cada etapa, es una buena práctica dejar comentado y documentado el código. Ya sea por si te toca a vos revisarlo dentro de mucho tiempo, o por si otra persona tiene que tomar tus procesos.
3. Fijate de usar nombres de variables mas descrptivos: por ejemplo "f_sql" y "s" no ayudan mucho a entender lo que estás guardando en cada objeto.

2022-06-29 02:01 UTC, juanmbntz requested changes
Nico, está bien la función. Te dejo dos comentarios:

1. Mismo que la otra tarjeta, agregale siempre mas comments a tu código.
2. Faltaría que este operador lo pushees integrado en un DAG.

2022-06-29 02:04 UTC, juanmbntz requested changes
Nico, ojo con el split_part de la columna "names" que te va a dejar ensuciar los datos. Vas a ver que no te quedas siempre con nombre y apellido usando esa forma.

2022-06-29 14:03 UTC, lugonesnicolas commented
Si como estoy teniendo problemas para filtrar entre las fechas con el between no agregue el proceso para el segundo archivo.
Si el operador lo tengo integrado en el dag no lo pushee para que puedas correguir esa parte, en seguida pusheo todo junto como me va quedando.

2022-06-30 00:40 UTC, juanmbntz requested changes
Nico, fijate que con el split part vas a terminar levantando datos sucios. Ojo que no todos los nombres te devuelven 2 campos al serparar con " - ".

2022-06-30 00:44 UTC, juanmbntz requested changes
Nico, en esta no veo el operador integrado en un DAG. Fijate que la tarjeta dice  "implementar". Fijate de integrarlo en el archivo con el DAG que estas armando.

2022-06-30 00:46 UTC, juanmbntz approved these changes
Nico, ignora el comentario de que no integraste el operador, aca vi el operador con la funcion de extraccion metido en le DAG! ja, disculpa!

2022-06-30 00:47 UTC, merged