OT235-96/97
alkemyTech/OT235-python pull request #28
Opened 2022-07-04 14:29 UTC by lugonesnicolas

Operadores S3 para las Universidades grupo G

2022-07-04 22:43 UTC, juanmbntz requested changes
Nico, buenismo! Consulta, me podras adjuntar por aca o en Jira algun print de pantalla para mostrar que funciona el codigo?

Tengo dudas de es "bucket" que pasas como string, asi como esta corre? No habria que poner el nombre del bucket?

Despues creo que te quedo lat_sociales en las dos responses. Fijate si lo podes acomodar porfa. Despues esta bien!

2022-07-05 02:15 UTC, lugonesnicolas commented
Juan te dejo un print de la función, no me arrojo ningún error.
![image](https://user-images.githubusercontent.com/82919404/177236281-10c2a18e-3cac-4391-8aab-8489e137f086.png)

2022-07-05 03:04 UTC, lugonesnicolas commented
De esta manera me da esto que creo que es porque no tengo una conexión a aws 
![image](https://user-images.githubusercontent.com/82919404/177241193-99a6f733-e110-42b2-84c0-7f7390db4b4e.png)

2022-07-05 03:05 UTC, lugonesnicolas commented
Y de esta manera me da lo mismo
![image](https://user-images.githubusercontent.com/82919404/177241427-982f5f0f-7059-458a-bd6a-174ad843f8ed.png)

2022-07-11 21:48 UTC, lugonesnicolas commented
Hola Juan ya pude generar un bucket y probar mi código.
![image](https://user-images.githubusercontent.com/82919404/178364529-f28b9932-4455-4e9c-9afe-6bdc865eebb9.png)

2022-07-11 22:46 UTC, juanmbntz requested changes
Nico, fijate de buscar otra forma de conectarte al S3 que no implique compartir las claves de acceso en el codigo. Acordate que no podemos compartir esas claves.

2022-07-11 22:47 UTC, closed without merging